version: "3.8"

services:

  postgresql:
    container_name: database
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=starwars
      - POSTGRES_USER=baggio
      - POSTGRES_PASSWORD=baggio
